{"name": "密码错误", "status": "broken", "statusDetails": {"message": "AttributeError: 'CaseData' object has no attribute 'casea_data'", "trace": "self = <autotest03.testcases.test_my_interface01.test_login.TestLogin object at 0x0406F310>\ncase = <comms.excel_utils.CaseData object at 0x04021160>\n\n    @allure.severity(\"critical\")  # 设置用例优先级\n    @pytest.mark.parametrize(\"case\", cases)\n    def test_login(self, case):  # 所有的测试方法必须以test开头\n        allure.dynamic.title(case.case_title)  # 动态获取用例名称,allure报告显示用例名称\n        allure.attach(body=case.url, name='接口路径')\n>       allure.attach(body=case.casea_data, name='请求参数')\nE       AttributeError: 'CaseData' object has no attribute 'casea_data'\n\ntest_login.py:30: AttributeError"}, "attachments": [{"name": "接口路径", "source": "b57f7b40-ce75-4310-a164-87c3935cb4fc-attachment.attach"}], "parameters": [{"name": "case", "value": "<comms.excel_utils.CaseData object at 0x04021160>"}], "start": 1646039094952, "stop": 1646039094952, "uuid": "b9c4310a-35ad-40dd-a377-c0ccbcd226d2", "historyId": "35cba699e993707adaf0182de89dc534", "testCaseId": "b62a022e3184708d2d40012e446c9b1d", "fullName": "test_login.TestLogin#test_login", "labels": [{"name": "feature", "value": "登录接口测试"}, {"name": "severity", "value": "critical"}, {"name": "suite", "value": "test_login"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "DESKTOP-V37VTV5"}, {"name": "thread", "value": "65284-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_login"}]}